### PR TITLE
Python and Django mid-to-senior software developer

### PR DESCRIPTION
**Pull request by pupeno**
Python and Django mid-to-senior software developer at a fintech company

### CODE REVIEW

**Comment by pupeno** [comment]
I just fixed an issue with the markdown formatting. Thanks for the screenshot, that helped.

**Comment by pupeno** [comment]
That looks good. Thank you.

**Comment by stestagg** [comment]
Hi. Thanks for the submission.  Should be live shortly

**Comment by stestagg** [comment]
One thing I just noticed. The submission date is set to apr 2018. This will make the advert appear quite far down the list. I would recommend updating it to be today

**Pull request merged**
