### PR TITLE
Create essentia_analytics_pgh3.html

### PR DESCRIPTION
**Pull request by jchall001**
Job add for Essentia Analytics

### CODE REVIEW

**Comment by salimfadhley** [comment]
You left the <> symbols around the name - those need to be removed before you can submit.

**Comment by salimfadhley** [comment]
I corrected your submittion and re-did it for you:

https://github.com/pythonjobs/jobs/pull/59

**Comment by jchall001** [comment]
brilliant thank you

**Comment by salimfadhley** [comment]
The location field is mandatory - what is the primary location for this job?

**Comment by jchall001** [comment]
London (Notting Hill)

**Comment by salimfadhley** [comment]
It should be added now.

**Pull request closed without merging**
