### PR TITLE
Add job posting for full stack developer at Arctic Shores.

### PR DESCRIPTION
**Pull request by safehammad**
With thanks!

### CODE REVIEW

**Comment by salimfadhley** [comment]
Thanks, your job has been posted

**Comment by safehammad** [comment]
Will you be able to merge the pull request? I don't see the job posting :) Thanks

**Comment by salimfadhley** [comment]
Strange, are you sure you made the pull request against the correct Repo?

**Comment by salimfadhley** [comment]
http://pythonjobs.github.io/jobs/arctic-shores-100.html

Live now! :-)

**Pull request merged**
