### PR TITLE
Create realrate-gmbh-senior-python-developer.html

### PR DESCRIPTION
**Pull request by karlb**

### CODE REVIEW

**Review by rs2 — APPROVED** [review]
LGTM

**Comment by rs2** [comment]
Will need to check the root cause behind the error

**Comment by karlb** [comment]
Thanks for reviewing and merging, but I don't see the job at http://pythonjobs.github.io/, yet. Shouldn't it be there after merging?

**Comment by rs2** [comment]
We are looking.

**Comment by lordmauve** [comment]
You have the timestamp set to `2018-04-25` which means it will appear very low down the list. This needs to be set to today's date.

**Pull request merged**
