### PR TITLE
Add: Yunojuno Django Developer in London

### PR DESCRIPTION
**Pull request by estellareed**
Thank you very much!

Estella.

### CODE REVIEW

**Comment by lordmauve** [comment]
The tests are failing because all files have to end in .html. I don't know why - might be a Hyde thing - but at least it's consistent.

**Comment by salimfadhley** [comment]
@estellareed do you need help with this?

**Comment by salimfadhley** [comment]
Estella, it looks like you are no longer interested in posting this. I'm going to close this for now.

**Comment by estellareed** [comment]
Hi @salimfadhley  - apologies! I 've only just got around to seeing this and new to this - would you be able to help as I really would like this to go live. Many thanks

**Pull request closed without merging**
