### PR TITLE
Create sartregroup_london_exppythondev.html

### PR DESCRIPTION
**Pull request by joe-jollySG**

### CODE REVIEW

**Comment by salimfadhley** [comment]
Can you please escape the ampersand characters, for example P&L should be written P&amp;L. One day we will add automatic HTML escaping but we don't have it yet.

**Comment by salimfadhley** [comment]
I'm going to close this one for now - if you could kindly resubmit with the ampersands fixed I will merge it.

**Comment by joe-jollySG** [comment]
Hi Salim,

I think I made the changes you suggested and have re-submitted – could you double check it’s okay?

Also, I already have another ad running on the site, however I needed to make a change to it, are you able to point out how best to do that?

Kind regards,

Joe Jolly

Sartre Group

[cid:image001.png@01D185E8.1D029370]<http://www.sartregroup.com/>

Email:              joe.jolly@sartregroup.com<mailto:joe.jolly@sartregroup.com>
US Tel:            +1    917 795 0584
UK Tel:            +44 (0) 203 457 8952
Corporate Headquarters           New York Office
4th Floor                                   280 Madison Avenue
68 Great Eastern Street             t#912
London                                    9th Floor
EC2A 3JT                                 NY 10016

www.sartregroup.com<http://www.sartregroup.com/>

[7b24d431-b33f-4266-8e00-6ec431907477]<https://uk.linkedin.com/in/tomhone>

Sartre Group is a company registered in England & Wales with Company Number 07920610.  This e-mail contains proprietary information some or all of which may be legally privileged. It is for the intended recipient only.  If an address or transmission error has misdirected this email, please notify the author by replying to this e-mail.  If you are not the intended recipient you must not use, disclose, distribute, copy, print, rely on or retain this e-mail. If you receive this email in error, please contact our postmaster on +44 (0)20 3478 4858. Sartre Group is in the business of introducing qualified candidates to potential employers.  Candidates and employers must assure that trade secrets or confidential information belonging to others are not used or disclosed during interviews, new employment positions, or any other time.  They also must be responsible for complying with any potentially valid covenants not to compete or other legal restrictions.  They should refer all questions on these matters to their own independent legal counsel.  All e-mails including CV's are subject to our standard terms and conditions of business.  The acceptance of any CV's constitutes the acceptance of our standard terms and conditions of business unless there has been written prior agreement.

**Comment by salimfadhley** [comment]
I will re-check

**Comment by salimfadhley** [comment]
Thanks for resubmitting.

**Pull request merged**
