### PR TITLE
Update partners-capital-senior-full-stack-contract-software-developer since there is some styling issue

### PR DESCRIPTION
**Pull request by ziyenl**
Update partners-capital-senior-full-stack-contract-software-developer since there is some styling issue

### CODE REVIEW

**Comment by ziyenl** [comment]
I'm having trouble changing it to proper bullet point. I tried using *, but it doesn't seem to work?

**Comment by lordmauve** [comment]
I think you need a blank line before and after each bulleted list.

**Comment by salimfadhley** [comment]
I will wait before merging this in - it looks like you've not yet fixed the problem.

**Comment by salimfadhley** [comment]
I'm going to merge this request because it's harmless, but I don't think your problem is fixed.

**Pull request merged**
