### PR TITLE
README.md: Add SSL to live page link

### PR DESCRIPTION
**Pull request by hartwork**
For people browsing at work but not only :)

The link next description `A repository for our international job listings` also needs an update but I can't do that from here...

### CODE REVIEW

**Comment by hartwork** [comment]
Is anything missing to have this merged?

**Comment by stestagg** [comment]
Nope, sorry, I pressed approve rather than merge, if it happens again, then feel free to merge :)

**Comment by hartwork** [comment]
Thanks! (PS: I don't have permissions to merge.)

**Comment by stestagg** [comment]
Aah, yeah, oops sorry

**Pull request merged**
